sap.ui.define([], function() {
	"use strict";

	return {
        Header:{
            Auart:"",
            FuncName:"",
            Vkorg:"",
            Vtweg:"",
            Spart:"",
            Vkbur:"",
            Vkgrp:"",
            Kunnr:"",
            Zterm:"",
            Orderno:"",
            Inco1:"",
            Inco2:"",
            Detail:[]
        },
        HeaderText:{
            AuartDesc:"",
            VkorgDesc:"",
            VtwegDesc:"",
            SpartDesc:"",
            VkburDesc:"",
            VkgrpDesc:"",
            CustomerName:"",
            ZtermDesc:"",
            Inco1Desc:""
        },
        Item:{
            Posnr:0,
            Material:"",
            MaterialDesc:"",
            Meins:"",
            RefDocNo:"",
            RefDocItm:"",
            ReqDate: null,
            Qty:0,
            UnitPrice:0,
            UnitCurr:"",
            Kscha:"",
            Price:"",
            Currency:"",
            Simulate:false,
            Usability:[]
        },
        Usability:{
            Posnr:"",
            ReqDate:null,
            ReqQty:null,
            Meins:null
        },
        mainView:{
            bEdit:true,
            bCustomerRef:false,
            delay:0
        }
    }
});